feat: add release and test workflows (#17)
* chore: prevent unneeded files in build

- No test files or fixtures because they were excluded in tsconfig.prod.json
- No dev dependencies because we do not install those
- No config files because we use the build dir as the project root

* chore: avoid showing env var warning for every thread

* chore: switch from yarn to npm and npx

* chore: use NODE_ENV variable instead of CONTEXT

* fix: prevent infinite restart loops when DHIS2 Core is not found

* chore: switch from build to dist dir for built artifacts

* fix: target dist dir in start-prod script

* feat: add streamlined docker container setup

* chore: add workflow to verify the app

* chore: refer to nodejs lts as `lts/*` in workflow

* chore: adjust readme to npm instead of yarn

* chore: add initial release-it setup

* chore: release v0.2.0

* chore: remove release-it because it did not work well for manually triggering releases

* fix: add commitlint and husky to avoid bad commit messages

* chore: format package-lock so pre-commit hooks pass

* chore: add lint step to the pre-commit hook

* chore: validate commit message in the commit-msg hook

* chore: add manually triggered action for releasing WIP

* chore: try to fix workflow syntax

* chore: add push trigger to workflow so hopefully it shows up

* chore: use lts nodejs so tests pass

* chore: prevent running other jobs if first fails

* fix: prevent other jobs running with exit codes in first job

* chore: check if workflow is working by allowing current branch name

* chore: disable push trigger, only keep workflow_dispatch

* chore: see if it shows up without inputs

* chore: adjust workflow temporary

* chore: compress the dist dir

* chore: add names to verify steps

* chore: remove versions to see if annotations are removed

* chore: update action versions to prevent warnings

* chore: echo file size after compression

* chore: adjust comments and formatting

* chore: try semantic-release dry-run

* chore: rename workflow

* chore: use default release branches

* chore: do not release on push or merge

* chore: prevent chatty output when ziping the dist dir

* chore: further tweak compression step output

* chore: allow alpha beta and next as release branches

* chore: allow arbitrary line length on commit body

* chore: drop semantic-release deps in favor of release-it

We want the package.json version to be updated in the repo. For release-it this is built-in behavior while this is being discouraged in the semantic-release docs. Also, semantic-release is very inflexible about version numbers, not allowing the initial release to be a `0.#.#`.

* chore: build app using a script and add typescript linting

* chore: add release-it config

* chore: tweak release-it config so it skips checking NPM (WIP)

* chore: rename release-it config and add current branch

* chore: tweak release-it config

* chore: remove current branch from allowed release list

* chore: use release-it in release workflow

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -1,12 +1,65 @@
 name: Release to GitHub and Docker Hub
 
+# We trigger releases manually
 on: workflow_dispatch
 
 jobs:
+    # TODO: re-enable this (it has been tested and works well)
+    # Only allow releases from the release branches branch
+    # check_if_allowed:
+    #     runs-on: ubuntu-latest
+    #     steps:
+    #         - name: Exit if branch is not a release branch
+    #           # Add more branches if we want to release from there
+    #           run: |
+    #               if [ "${{ github.ref }}" = "refs/heads/master" ] || \
+    #                  [ "${{ github.ref }}" = "refs/heads/alpha" ] || \
+    #                  [ "${{ github.ref }}" = "refs/heads/beta" ] || \
+    #                  [ "${{ github.ref }}" = "refs/heads/next" ] ||
+    #               then
+    #                   echo "On the master branch, release is allowed"
+    #                   exit 0
+    #               else
+    #                   echo "Releases are only allowed from the master branch"
+    #                   exit 1
+    #               fi
+
     create_github_release:
+        # Will not run if check_if_allowed fails
+        # needs: check_if_allowed
         runs-on: ubuntu-latest
         steps:
             - name: Checkout repo
               uses: actions/checkout@v4
-            - name: Hello world
-              run: echo "Hellow world"
+            - name: Setup NodeJS
+              uses: actions/setup-node@v4
+              with:
+                  node-version: lts/*
+                  cache: 'npm'
+            - name: Install dependencies
+              run: npm ci --include=dev
+            - name: Release
+              env:
+                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+              run: npx -y release-it --ci
+
+    # Create zip from build
+    # Create GitHub release with changelog and include zip
+    # Deploy to docker-hub
+
+    # publish-gpr:
+    #     needs: build
+    #     runs-on: ubuntu-latest
+    #     permissions:
+    #         contents: read
+    #         packages: write
+    #     steps:
+    #         - uses: actions/checkout@v4
+    #         - uses: actions/setup-node@v4
+    #           with:
+    #               node-version: 16
+    #               registry-url: https://npm.pkg.github.com/
+    #         - run: npm ci
+    #         - run: npm publish
+    #           env:
+    #               NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
